### ISSUE TITLE
v1.0 throws an error at launch about hlnonvr.exe

### ISSUE THREAD

**Issue by mrtino** [jean-knapp/xblah-modding-tool#48]
Steps to reproduce:
- Install Half-Life: Alyx on the C: drive
- Run Modding Tools and see .NET Framework throw an error at launch about hlnonvr.exe not being found.

```
System.IO.FileNotFoundException: C:\Program Files (x86)\Steam\steamapps\common\Half-Life Alyx\game\bin\win64\hlnonvr.exe
   at System.Drawing.Icon.ExtractAssociatedIcon(String filePath, Int32 index)
   at source_modding_tool.MainForm.updateToolsGames()
   at source_modding_tool.MainForm.Form_Load(Object sender, EventArgs e)
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at DevExpress.XtraEditors.XtraForm.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at DevExpress.XtraEditors.XtraForm.WndProc(Message& msg)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```
Existing mods aren't found until you create a new one, probably because of that.

**Comment by jean-knapp** [comment]
Ugh, I'm already making a check to see if this file exists, it shouldn't throw this error.

![image](https://user-images.githubusercontent.com/81480122/149241415-dcc9ce59-456d-409f-a9ff-a172f8d0f16b.png)

**Comment by jean-knapp** [comment]
Well, just to be sure, I replaced it to this code. Reopen this issue if the next version doesn't fix this.

![image](https://user-images.githubusercontent.com/81480122/149241510-6b6b039d-d528-4092-b371-1e5728dba189.png)
