### ISSUE TITLE
I cannot select my mod on the dropdown menu

### ISSUE THREAD

**Issue by miifanboy** [jean-knapp/xblah-modding-tool#54]
I launched the program then selected half life 2 multiplayer and created a mod for Counter Strike: Source but it gave me an error as soon as i hit create button I will try to fix it myself the problem but i am creating this issue to let the developers know the bug.

![image](https://user-images.githubusercontent.com/87207112/146641329-26f8a956-3fe5-476a-abc2-a495964ef79d.png)

![image](https://user-images.githubusercontent.com/87207112/146641337-233218ae-6265-4638-b77a-df53c92c643c.png)

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at source_modding_tool.MainForm.menuFile_ItemClick(Object sender, ItemClickEventArgs e)
   at DevExpress.XtraBars.BarItem.OnClick(BarItemLink link)
   at DevExpress.XtraBars.BarButtonItem.OnClick(BarItemLink link)
   at DevExpress.XtraBars.BarItemLink.OnLinkClick()
   at DevExpress.XtraBars.BarButtonItemLink.OnLinkClick()
   at DevExpress.XtraBars.BarItemLink.OnLinkAction(BarLinkAction action, Object actionArgs)
   at DevExpress.XtraBars.BarButtonItemLink.OnLinkAction(BarLinkAction action, Object actionArgs)
   at DevExpress.XtraBars.ViewInfo.BarSelectionInfo.ClickLink(BarItemLink link)
   at DevExpress.XtraBars.ViewInfo.BarSelectionInfo.UnPressLink(BarItemLink link)
   at DevExpress.XtraBars.Controls.CustomLinksControl.OnMouseUp(MouseEventArgs e)
   at DevExpress.XtraBars.Controls.CustomPopupBarControl.OnMouseUp(MouseEventArgs e)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at DevExpress.XtraBars.Controls.CustomControl.WndProc(Message& msg)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4420.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
XBLAH's Modding Tool
    Assembly Version: 1.4.0.0
    Win32 Version: 1.4.0.0
    CodeBase: file:///D:/indirilenler/Release/XBLAH's%20Modding%20Tool.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4400.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4360.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4390.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
DevExpress.Utils.v20.2
    Assembly Version: 20.2.6.0
    Win32 Version: 20.2.6.0
    CodeBase: file:///D:/indirilenler/Release/Libs/DevExpress.Utils.v20.2.DLL
----------------------------------------
DevExpress.Data.v20.2
    Assembly Version: 20.2.6.0
    Win32 Version: 20.2.6.0
    CodeBase: file:///D:/indirilenler/Release/Libs/DevExpress.Data.v20.2.DLL
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4190.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4390.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
DevExpress.Data.Desktop.v20.2
    Assembly Version: 20.2.6.0
    Win32 Version: 20.2.6.0
    CodeBase: file:///D:/indirilenler/Release/Libs/DevExpress.Data.Desktop.v20.2.DLL
----------------------------------------
DevExpress.XtraBars.v20.2
    Assembly Version: 20.2.6.0
    Win32 Version: 20.2.6.0
    CodeBase: file:///D:/indirilenler/Release/Libs/DevExpress.XtraBars.v20.2.DLL
----------------------------------------
DevExpress.XtraEditors.v20.2
    Assembly Version: 20.2.6.0
    Win32 Version: 20.2.6.0
    CodeBase: file:///D:/indirilenler/Release/Libs/DevExpress.XtraEditors.v20.2.DLL
----------------------------------------
System.ComponentModel.DataAnnotations
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.ComponentModel.DataAnnotations/v4.0_4.0.0.0__31bf3856ad364e35/System.ComponentModel.DataAnnotations.dll
----------------------------------------
SourceSDK
    Assembly Version: 1.5.0.0
    Win32 Version: 1.5.0.0
    CodeBase: file:///D:/indirilenler/Release/Libs/SourceSDK.DLL
----------------------------------------
UIAutomationClient
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4390.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/UIAutomationClient/v4.0_4.0.0.0__31bf3856ad364e35/UIAutomationClient.dll
----------------------------------------
UIAutomationTypes
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4390.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/UIAutomationTypes/v4.0_4.0.0.0__31bf3856ad364e35/UIAutomationTypes.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4270.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
DevExpress.XtraLayout.v20.2
    Assembly Version: 20.2.6.0
    Win32 Version: 20.2.6.0
    CodeBase: file:///D:/indirilenler/Release/Libs/DevExpress.XtraLayout.v20.2.DLL
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
```

When I try to access this mod even though it is present in my file explorer, I cannot access it through the program.

![image](https://user-images.githubusercontent.com/87207112/146641450-0d529eaf-619c-4c19-9283-b0ae19e8012a.png)

![image](https://user-images.githubusercontent.com/87207112/146641454-aba0d7a1-ba92-448e-a3a0-98cade2a866b.png)

Additional Info :
It shows me duplicate libraries:

![image](https://user-images.githubusercontent.com/87207112/146641486-09407c72-9597-4b99-b079-c0ac0e5bbdbf.png)

**Comment by jean-knapp** [comment]
Post your game info. The tool (and game) must identify it's a counter-strike source mod.

**Comment by jean-knapp** [comment]
No response, gameinfo is probably broken.
